### ISSUE TITLE
Network switcher

### ISSUE THREAD

**Issue by brandonhaslegs** [drips-network/app#1073]
We're gonna have a few networks 🔜

**Comment by brandonhaslegs** [comment]
I have a few options:

Header
<img width="475" alt="image" src="https://github.com/drips-network/app/assets/4406983/8b828873-32cd-4845-8383-48c09d603098">

Settings
<img width="1149" alt="image" src="https://github.com/drips-network/app/assets/4406983/051684f7-2abd-4233-98dd-c8c19e81a704">

Account/wallet dropdown
<img width="383" alt="image" src="https://github.com/drips-network/app/assets/4406983/6b7bbd4b-a911-473c-83bd-7ea216a614c5">

**Comment by efstajas** [comment]
IMO in settings it's too hidden

I think we need to think about disconnected & connected states separately. Maybe in disconnected, we could have the dropdown on the header, and move it to the account menu once connected (because at that point the network choice is anyway dictated by the wallet). Looks good otherwise, i think it's a good idea to make custom drips-style icons for each network.

**Comment by efstajas** [comment]
#1120
