### ISSUE TITLE
Get rid of strange /app/index.html search result on Google

### ISSUE THREAD

**Issue by brandonhaslegs** [drips-network/app#1079]
<img width="551" alt="image" src="https://github.com/drips-network/app/assets/4406983/368c2134-fb82-4090-b69f-41abbf3d14c3">

**Comment by brandonhaslegs** [comment]
Weird, it does have a title and description?
<img width="609" alt="image" src="https://github.com/drips-network/app/assets/4406983/1334f109-5146-45de-9371-ef8e33abbdd4">

**Comment by efstajas** [comment]
The explore page for sure has a title and description, so not sure what that first result is. Feel free to reopen with more detail

**Comment by brandonhaslegs** [comment]
if you google "Drips network" you can find this result

<img width="728" alt="image" src="https://github.com/drips-network/app/assets/4406983/9a984884-1335-4fa4-bfad-7749ecf0f91b">

**Comment by efstajas** [comment]
IDK where that came from, maybe it's a holdover from V1. The URL for that result is actually `https://www.drips.network/app/index.html`. Either way, the reason it's still in the index is proably that our app doesn't produce a proper 404 status for error pages on the profile like this. This is already fixed on the upcoming API refactor i'm working on, because the profile info will be loaded server-side, so the server will have an opportunity to send a 404. Once that's merged, i'll request a re-index of that URL from Google and it should be gone in max a few weeks.

**Comment by brandonhaslegs** [comment]
It appears to be fixed
