### ISSUE TITLE
Hide Projects and Drip Lists

### ISSUE THREAD

**Issue by brandonhaslegs** [drips-network/app#1242]
![image](https://github.com/user-attachments/assets/6b23d24b-8c3c-48a3-96e3-b7753824ac13)

Since we've made so many test projects on chain, we need a way to hide them too.

Also want to be able to hide the test stuff I've done on mainnet 🥺

<img width="592" alt="image" src="https://github.com/user-attachments/assets/ff1956b8-f90a-45e5-97a2-96c861eceb5c">

**Comment by efstajas** [comment]
So here's how I'm thinking to do this.

**Generally**
- Hidden projects or Drip Lists don't appear on "all projects / lists" screens.
- They also don't appear on public profiles.
- They appear on your personal dashboard, but only if the "show hidden" toggle is enabled, as per the designs.
- When trying to split to a hidden Drip List or Project, the list editor should display an error like "The List / Project is hidden and cannot be split to".
- If someone or something is already splitting / streaming to a now-hidden list or project, that stream and split DOES get displayed on the respective project / drip list / profile pages, BUT the split recipient / stream should be slightly greyed out with a warning icon.
- When directly accessing a hidden list or project via URL, it should render the page, but with a large warning at the top that says that it has been hidden and in case of a list, possibly transferred to the recipient (with learn more link to docs.
  - We shouldn't make them outright 404s, because these hidden entities may still be receiving and splitting funds. It's important that the platform remains fully transparent and flow of funds can't be entirely hidden in this way.
- Pages for hidden entities have meta that prevents them from being indexed by search engines. 

**Project visibility**
This one is simple. When you're in control of a project, you can set a `visible` boolean in metadata to `false`. Event processor should index this, and API should return a `visible` boolean in project data. If true, app treats it as hidden as described above.

**Drip Lists**
A bit more complicated, because we also want lists to be hidden by default when transferred to you. I'm thinking:
- When minting a new list, it sets a `visible` boolean to `true` in metadata.
- When the list metadata is being indexed, event-processor stores `visible: true` for the list. This is also exposed by the API.
- If a `transfer` event is indexed subsequently (aka the list is transferred), event processor checks if the new owner of the list previously published metadata for the same list where `visible` was set to `true`. If yes, the list remains set to visible in the DB. If not, the list is updated in the DB as invisible.
- If a subsequent metadata update event for the list is indexed that sets `visible` to `true` once more, event processor once again updates the list as visible in metadata.
- If at any point a metadata update is indexed where `visible` is set to `false`, event processor always updates the list as invisible in the DB.

That way, Drip Lists are visible after minting, can be hidden at will, and also are hidden by default after being transferred to someone else.

**Comment by brandonhaslegs** [comment]
> When trying to split to a hidden Drip List or Project, the list editor should display an error like "The List / Project is hidden and cannot be split to".

would be cool if you could still split to a hidden list. for privacy's sake, some people might want to do this

**Comment by efstajas** [comment]
> > When trying to split to a hidden Drip List or Project, the list editor should display an error like "The List / Project is hidden and cannot be split to".
> 
> would be cool if you could still split to a hidden list. for privacy's sake, some people might want to do this

Idk. It wouldn't be private at all — the info would still be visible on-chain and even our API, just marked as hidden, so it'd be an illusion of privacy at best.

**Comment by brandonhaslegs** [comment]
> > > When trying to split to a hidden Drip List or Project, the list editor should display an error like "The List / Project is hidden and cannot be split to".
> > 
> > 
> > would be cool if you could still split to a hidden list. for privacy's sake, some people might want to do this
> 
> Idk. It wouldn't be private at all — the info would still be visible on-chain and even our API, just marked as hidden, so it'd be an illusion of privacy at best.

we have to make that clear regardless

**Comment by brandonhaslegs** [comment]
> in case of a list, possibly transferred to the recipient
what do you mean? how could being hidden also be the same state as transferred?

**Comment by efstajas** [comment]
> > in case of a list, possibly transferred to the recipient
> 
> what do you mean? how could being hidden also be the same state as transferred?

If we go with what I propose above, lists would be hidden automatically when transferred and would remain that way until explicitly set to visible by the new owner.

**Comment by efstajas** [comment]
@brandonhaslegs when you have capacity, could you update the designs with the above in mind?

need to know what splits & streams to hidden things look like, what viewing a hidden drip list or project looks like, and also probably update the visibility toggle to explain things clearer (no expectation of privacy etc.) 

I'd also write up a docs page for that so we can link to it.

**Comment by brandonhaslegs** [comment]
All else sounds great to me!

**Comment by brandonhaslegs** [comment]
Drip List
![Image](https://github.com/user-attachments/assets/215d92c9-2525-41bb-8d36-85620bd2ccd6)

Project
![Image](https://github.com/user-attachments/assets/cbff0485-2fb1-4458-a94f-b502d6401481)

Can comment or look at the full design [here](https://www.figma.com/design/vyI7f996JF8zwhnXwAwXdC/%F0%9F%92%A7-Drips?node-id=11602-33849&t=Zzh1kC3sh6m5mf6G-1)

Worth noting that the support card would be gone when in the hidden state.

**Comment by brandonhaslegs** [comment]
Update design and wording to

![Image](https://github.com/user-attachments/assets/13ea3fcc-f131-4448-a968-6f357efba623)
