### ISSUE TITLE
Is this stuff supposed to be white? 

### ISSUE THREAD

**Issue by brandonhaslegs** [drips-network/app#606]
Is there a white color in this theme? I thought everything was green

<img width="634" alt="Screenshot 2023-07-28 at 08 53 28" src="https://github.com/radicle-dev/drips-app-v2/assets/4406983/9949d828-dbb1-482e-92f0-c7f724435c90">

**Comment by efstajas** [comment]
it's a bit of a strange situation - some elements that put something on `color-primary` choose either black or white text depending on contrast to `color-primary` rather than just using `color-foreground`, in order to ensure legibility in the context of a project theme. some primary colors there need white text on buttons instead of color-foreground, but we don't explicitly define an entire theme for projects - just the primary color. 

the way to fix it would be to actually define an entire set of theme variables for each possible project color.

the "100% allocated" thing is just themed as `color-primary-level-6`

**Comment by brandonhaslegs** [comment]
Don't care
