### ISSUE TITLE
netlify PR deploys block merging outside contributors forked repositories

### ISSUE THREAD

**Issue by evvvritt** [drips-network/app#676]
@efstajas, I approved an outside contributor's PR but it can't be merged because Netlify isn't deploying his forked repository perhaps? 

<img width="1539" alt="Screenshot 2023-09-20 at 18 36 27" src="https://github.com/drips-network/app/assets/6071219/6e9c55c3-a8b0-42f3-87a6-5bce8b3fcd88">

**Comment by efstajas** [comment]
Hey @evvvritt, Netlify currently only deploys previews for external contributions once explicitly approved within the Netfliy interface so that no-one can just spam a bunch of PRs and eat up all our build time. I've just approved all the pending deploys on Netfliy. You should be able to do the same with your access, I believe, but lmk if that's not the case.

We could also just set it to deploy everything until it actually becomes a problem. Wdyt?

**Comment by evvvritt** [comment]
Oki, can manually approve. Didn't realize I had access.
