### ISSUE TITLE
Social share text

### ISSUE THREAD

**Issue by brandonhaslegs** [drips-network/app#98]
In addition to #97 the text in the link preview should also be customized to display relevant information about the link you're sharing. Maybe the dripper, drippee, amount being dripped per day. Maybe this is easier to do than the social image share thing.

Examples:

<img width="385" alt="image" src="https://user-images.githubusercontent.com/4406983/201892998-c2b72163-b916-4e1e-b877-915ae1423089.png">
<img width="252" alt="image" src="https://user-images.githubusercontent.com/4406983/201893561-5585fb99-6b2e-45bc-b3d9-5581373c069d.png">
<img width="348" alt="image" src="https://user-images.githubusercontent.com/4406983/201895976-3f19fd40-6f7b-44a2-9bf9-b062ef491954.png">

**Comment by brandonhaslegs** [comment]
Is this really completed?

**Comment by efstajas** [comment]
Woops, went over open issues with Everett earlier and accidentally marked as completed just based on the title 🙂

**Comment by brandonhaslegs** [comment]
Should also add the image preview work to this. 
![image](https://github.com/drips-network/app/assets/4406983/6c5d846f-4cac-4c88-a4be-02c2e423b8de)

**Comment by efstajas** [comment]
@brandonhaslegs could you add here specific text templates for the different pages and mark it as "good first issue"?

**Comment by efstajas** [comment]
@brandonhaslegs I like all of these generally, but I would remove the donation dollar amounts. They fluctuate a ton and these share texts are barely if ever updated by social networks. I'm pretty sure Telegram for example never updates them on its own. That'd mean that some project that was shared _once_ by anyone while unclaimed would appear as having 0 donations forever, even if it received a million dollars later. 

I think rule of thumb should be that the share texts should never look "bad" even if outdated. For example, an unclaimed project should appear with just its description, rather than as "unclaimed" or "splitting to 0 dependencies". Not that you suggested otherwise, but just an example.

**Comment by efstajas** [comment]
Telegram also caches these share texts for a long time, generally. there's even a "website bot" that you can use to manually refresh share data for a particular URL.

If twitter profile edits really apply immediately, they must have some system that tells telegram about edits and makes them bust the cache of the share data. Or maybe Telegram caches much less for large well known services like Twitter.

For us, guaranteed that the share data would practically never update once in the cache.
